export const CROPPER_TICK = "CROPPER/TICK" as const;
export const CROPPER_COMPLETE = "CROPPER/COMPLETE" as const;

// Container

export const CROPPER_UPDATE_DISPLAYABLE_RECT = "CROPPER/CONTAINER/UPDATE_RECT" as const;

// Cropper

export const CROPPER_CROPPER_START_DRAG = "CROPPER/CROPPER/START_DRAG" as const;
export const CROPPER_CROPPER_START_TRANSFORM = "CROPPER/CROPPER/START_TRANSFORM" as const;
export const CROPPER_CROPPER_CHANGE_ASPECT_RATIO = "CROPPER/CROPPER/CHANGE_ASPECT_RATIO" as const;
export const CROPPER_CROPPER_CHANGE_FREE_ASPECT_RATIO = "CROPPER/CROPPER/CHANGE_FREE_ASPECT_RATIO" as const;

// Images

export const CROPPER_IMAGE_INITIALIZE = "CROPPER/IMAGE/INITIALIZE" as const;
export const CROPPER_IMAGE_START_TRANSFORM = "CROPPER/IMAGE/START_TRANSFORM" as const;
