export const APPENDABLE_STICKERS = [
  {
    name: "",
    imageUrl: "/images/pages/stickers/special.svg",
    url: null,
    urls: [
      "/images/stickers/3/1.png",
      "/images/stickers/3/2.png",
      "/images/stickers/3/3.png",
      "/images/stickers/3/4.png",
      "/images/stickers/3/5.png",
      "/images/stickers/3/6.png",
      "/images/stickers/3/7.png",
      "/images/stickers/3/8.png",
      "/images/stickers/3/9.png",
      "/images/stickers/3/10.png",
      "/images/stickers/3/11.png",
      "/images/stickers/3/12.png",
      "/images/stickers/3/13.png",
      "/images/stickers/3/14.png",
      "/images/stickers/3/15.png",
      "/images/stickers/3/16.png",
      "/images/stickers/3/17.png",
      "/images/stickers/3/18.png",
    ],
  },
  {
    name: "かるめりちゃんスタンプ",
    imageUrl: "/images/pages/stickers/line-store.svg",
    url: "https://store.line.me/stickershop/product/6457012/ja",
    urls: [
      "/images/stickers/1/1.png",
      "/images/stickers/1/2.png",
      "/images/stickers/1/3.png",
      "/images/stickers/1/4.png",
      "/images/stickers/1/5.png",
      "/images/stickers/1/6.png",
      "/images/stickers/1/7.png",
      "/images/stickers/1/8.png",
      "/images/stickers/1/9.png",
      "/images/stickers/1/10.png",
      "/images/stickers/1/11.png",
      "/images/stickers/1/12.png",
      "/images/stickers/1/13.png",
      "/images/stickers/1/14.png",
      "/images/stickers/1/15.png",
      "/images/stickers/1/16.png",
    ],
  },
  {
    name: "かるめりちゃんスタンプ 2",
    imageUrl: "/images/pages/stickers/line-store.svg",
    url: "https://store.line.me/stickershop/product/9903456/ja",
    urls: [
      "/images/stickers/2/1.png",
      "/images/stickers/2/2.png",
      "/images/stickers/2/3.png",
      "/images/stickers/2/4.png",
      "/images/stickers/2/5.png",
      "/images/stickers/2/6.png",
      "/images/stickers/2/7.png",
      "/images/stickers/2/8.png",
      "/images/stickers/2/9.png",
      "/images/stickers/2/10.png",
      "/images/stickers/2/11.png",
      "/images/stickers/2/12.png",
      "/images/stickers/2/13.png",
      "/images/stickers/2/14.png",
      "/images/stickers/2/15.png",
      "/images/stickers/2/16.png",
      "/images/stickers/2/17.png",
      "/images/stickers/2/18.png",
      "/images/stickers/2/19.png",
      "/images/stickers/2/20.png",
      "/images/stickers/2/21.png",
      "/images/stickers/2/22.png",
      "/images/stickers/2/23.png",
      "/images/stickers/2/24.png",
    ],
  },
];
