export const useRouter = jest.fn(() => ({
  asPath: "/",
  back: jest.fn(),
  basePath: "",
  beforePopState: jest.fn(),
  defaultLocale: "ja",
  events: {},
  isFallback: false,
  isLocaleDomain: false,
  isPreview: false,
  isReady: true,
  locale: "en",
  locales: ["en", "ja"],
  pathname: "/",
  prefetch: jest.fn(),
  push: jest.fn(),
  query: {},
  reload: jest.fn(),
  replace: jest.fn(),
  route: "/",
}));
