export const SET_SVG_POSITION_AND_SIZE = "CANVAS/CONTAINER/SET_SVG_POSITION_AND_SIZE" as const;

export const TICK = "CANVAS/TICK" as const;
export const COMPLETE = "CANVAS/COMPLETE" as const;
export const SET_FRAME = "CANVAS/SET_FRAME" as const;
export const ADD_USER_IMAGE_AND_SET_FRAME = "CANVAS/ADD_USER_IMAGE_AND_SET_FRAME" as const;
export const SET_DEFAULT_FRAME = "CANVAS/SET_DEFAULT_FRAME" as const;

export const ADD = "CANVAS/CANVAS_STICKER_LAYER/ADD" as const;
export const REMOVE = "CANVAS/CANVAS_SRICKER_LAYER/REMOVE" as const;
export const SET_ACTIVE = "CANVAS/CANVAS_STICKER_LAYER/SET_ACTIVE" as const;
export const START_DRAG = "CANVAS/CANVAS_STICKER_LAYER/START_DRAG" as const;
export const START_TRANSFORM = "CANVAS/CANVAS_STICKER_LAYER/START_TRANSFORM" as const;

export const USER_ADD = "CANVAS/CANVAS_USER_LAYER/USER_ADD" as const;
export const USER_REMOVE = "CANVAS/CANVAS_USER_LAYER/USER_REMOVE" as const;
export const USER_START_DRAG = "CANVAS/CANVAS_USER_LAYER/USER_START_DRAG" as const;
export const USER_SET_POSITION = "CANVAS/CANVAS_USER_LAYER/USER_SET_POSITION" as const;
export const FILTER_SET_VALUE = "CANVAS/CANVAS_FILTER/SET_VALUE" as const;
