export const CANVAS_INITIALIZE = "CANVAS/INITIALIZE" as const;
export const CANVAS_COMPLETE = "CANVAS/COMPLETE" as const;
export const CANVAS_ENABLE_COLLAGE = "CANVAS/ENABLE_COLLAGE" as const;
export const CANVAS_DISABLE_COLLAGE = "CANVAS/DISABLE_COLLAGE" as const;

// Containers

export const CANVAS_CONTAINER_UPDATE_RECT = "CANVAS/CONTAINER/UPDATE_RECT" as const;

// Stickers

export const CANVAS_STICKER_LAYER_ADD = "CANVAS/CANVAS_STICKER_LAYER/ADD" as const;
export const CANVAS_SRICKER_LAYER_REMOVE = "CANVAS/CANVAS_SRICKER_LAYER/REMOVE" as const;
export const CANVAS_STICKER_LAYER_START_DRAG = "CANVAS/CANVAS_STICKER_LAYER/START_DRAG" as const;
export const CANVAS_STICKER_LAYER_START_TRANSFORM = "CANVAS/CANVAS_STICKER_LAYER/START_TRANSFORM" as const;
export const CANVAS_STICKER_LAYER_TICK = "CANVAS/CANVAS_STICKER_LAYER/TICK" as const;
export const CANVAS_STICKER_LAYER_CHANGE_ORDER = "CANVAS/CANVAS_STICKER_LAYER/CHANGE_ORDER" as const;

// Users

export const CANVAS_USER_LAYER_ADD = "CANVAS/CANVAS_USER_LAYER/ADD" as const;
export const CANVAS_USER_LAYER_REMOVE = "CANVAS/CANVAS_USER_LAYER/REMOVE" as const;
export const CANVAS_USER_LAYER_START_DRAG = "CANVAS/CANVAS_USER_LAYER/START_DRAG" as const;
export const CANVAS_USER_LAYER_TICK = "CANVAS/CANVAS_USER_LAYER/TICK" as const;
export const CANVAS_USER_LAYER_UPDATE_FILTER = "CANVAS/CANVAS_USER_LAYER/UPDATE_FILTER" as const;
