export const UI_CHANGE_FILTER_TYPE = "UI/CHANGE_FILTER" as const;
export const UI_IMAGE_LOAD_ERROR = "UI/IMAGE_LOAD_ERROR" as const;
export const UI_IMAGE_LOAD_ERROR_RESOLVE = "UI/IMAGE_LOAD_ERROR_RESOLVE" as const;
